### ISSUE TITLE
Feature request: post tasks to front of queue (LIFO)?

### ISSUE THREAD

**Issue by emmenlau** [inkooboo/thread-pool-cpp#21]
I need to prefer new tasks over old tasks in the queue. Is it possible to change the mpmc queue to post to the front of the queue, or to add a new method post_front()?

**Comment by inkooboo** [comment]
It is possible to use your own stack container implementation instead of FIFO queue.
It should implement same interface and give same thread-safety guaranties as mpmc queue does.

Then you can define desired thread pool specialization like here:
https://github.com/inkooboo/thread-pool-cpp/blob/master/include/thread_pool/thread_pool.hpp#L16-L19

Really appreciate if you can submit PR with some good stack container added.

**Comment by emmenlau** [comment]
Dear @inkooboo thanks for the pointer! Is there any chance that you could help me implement such a container? I am hesitant to ensure the thread-safety guarantees.

**Comment by inkooboo** [comment]
@emmenlau Well, implementing things like lock-fee containers is really tricky and error-prone. I would not do it myself as well (because I'm not good enough for it.). It is better to take some well-known existing algorithm/implementation and adopt it, as I did for MPMC queue. Of course I'll help you as much as I can. Thanks.

**Comment by emmenlau** [comment]
@inkooboo ok I very much understand and relate to this. Then I will need to see if I can find external programmers help. Should I close this issue until someone can commit to this feature request?

**Comment by inkooboo** [comment]
No worries, let it be to track the progress. May be some day I'll have time and do it myself.

**Comment by emmenlau** [comment]
I guess this can be closed now.
