### ISSUE TITLE
c++11 support

### ISSUE THREAD

**Issue by headupinclouds** [inkooboo/thread-pool-cpp#3]
I am interested in using this with c++11 projects.  It seems the only feature requiring c++14 is the capture-by-move initialization for the packaged_task lambda assignment here:

https://github.com/inkooboo/thread-pool-cpp/blob/master/thread_pool/thread_pool.hpp#L117

I'll need to familiarize myself with this.  It seems a workaround might be possible in c++11 based on this document ("evil_wrapper"):

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3610.html

I'll take a look.  Any suggestions are welcome.

**Comment by inkooboo** [comment]
Yes, this is only place where c++14 needed. And yes, there exist a set of workarounds in C++11 to do the same task.
I prefer to keep code as is, with C++14 syntax. Because of:
* we live in 2015 year
* stable versions of GCC and Clang support this syntax for many years with "std=C++1y" parameter set.

**Comment by headupinclouds** [comment]
Ok, understood -- just a constraint I have to deal with for Android platforms.  Thanks again.

**Comment by inkooboo** [comment]
That should be fine. NDK has [GCC 4.8 and 4.9, Clang 3.5 and 3.6](http://developer.android.com/intl/ru/ndk/guides/standalone_toolchain.html). All these compilers support "std=C++1y" and capture-by-move initialization in lambdas.
